package com.github.jaideepaher.slatebrowser.compose

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.toArgb

val primaryLight = Color(0xFF0059BB)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF0070EA)
val onPrimaryContainerLight = Color(0xFFFEFCFF)
val secondaryLight = Color(0xFF445E91)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFA9C4FD)
val onSecondaryContainerLight = Color(0xFF355082)
val tertiaryLight = Color(0xFF954A00)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFF8200)
val onTertiaryContainerLight = Color(0xFF5F2C00)
val errorLight = Color(0xFFB81311)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFDC3128)
val onErrorContainerLight = Color(0xFFFFFBFF)
val backgroundLight = Color(0xFFFFFFFF)
val onBackgroundLight = Color(0xFF202124)
val surfaceLight = Color(0xFFFFFFFF)
val onSurfaceLight = Color(0xFF202124)
val surfaceVariantLight = Color(0xFFF1F3F4)
val onSurfaceVariantLight = Color(0xFF5F6368)
val outlineLight = Color(0xFF80868B)
val outlineVariantLight = Color(0xFFDADCE0)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF303134)
val inverseOnSurfaceLight = Color(0xFFF1F3F4)
val inversePrimaryLight = Color(0xFFADC7FF)
val surfaceDimLight = Color(0xFFDADCE0)
val surfaceBrightLight = Color(0xFFFFFFFF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF8F9FA)
val surfaceContainerLight = Color(0xFFF1F3F4)
val surfaceContainerHighLight = Color(0xFFE8EAED)
val surfaceContainerHighestLight = Color(0xFFE2E3E5)

val primaryDark = Color(0xFFADC7FF)
val onPrimaryDark = Color(0xFF002E68)
val primaryContainerDark = Color(0xFF4A8EFF)
val onPrimaryContainerDark = Color(0xFF000516)
val secondaryDark = Color(0xFFADC7FF)
val onSecondaryDark = Color(0xFF102F5F)
val secondaryContainerDark = Color(0xFF2D487A)
val onSecondaryContainerDark = Color(0xFF9EB8F1)
val tertiaryDark = Color(0xFFFFB785)
val onTertiaryDark = Color(0xFF502400)
val tertiaryContainerDark = Color(0xFFFF8200)
val onTertiaryContainerDark = Color(0xFF5F2C00)
val errorDark = Color(0xFFFFB4A9)
val onErrorDark = Color(0xFF690002)
val errorContainerDark = Color(0xFFFF5545)
val onErrorContainerDark = Color(0xFF450001)
val backgroundDark = Color(0xFF202124)
val onBackgroundDark = Color(0xFFE8EAED)
val surfaceDark = Color(0xFF202124)
val onSurfaceDark = Color(0xFFE8EAED)
val surfaceVariantDark = Color(0xFF3C4043)
val onSurfaceVariantDark = Color(0xFFBDC1C6)
val outlineDark = Color(0xFF9AA0A6)
val outlineVariantDark = Color(0xFF5F6368)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE8EAED)
val inverseOnSurfaceDark = Color(0xFF303134)
val inversePrimaryDark = Color(0xFF005BC0)
val surfaceDimDark = Color(0xFF202124)
val surfaceBrightDark = Color(0xFF3C4043)
val surfaceContainerLowestDark = Color(0xFF17181A)
val surfaceContainerLowDark = Color(0xFF292A2D)
val surfaceContainerDark = Color(0xFF303134)
val surfaceContainerHighDark = Color(0xFF3C4043)
val surfaceContainerHighestDark = Color(0xFF474A4E)

/**
 * Converts a [Color] to an RGB Hex String.
 */
fun Color.toRgbHexString(): String = toArgb().toHexString().substring(2)
